### ISSUE TITLE
hostHaloID is -1 for FoF Halo

### ISSUE THREAD

**Issue by jacobseiler** [manodeep/astro3D#2]
(Just a note for myself so I can remember)

Looking at the new Genesis tree format, `hostHaloID` (the analog for `FirstHaloInFOFgroup`) has been changed to be -1 for a FoF Halo.  A core assumption in `treefrog_to_lhalo.py` is that this instead points to itself.  This is causing issues with (at least currently) infinite loops after fixing the flybys.

Will need to check how this assumption propagates through the code and fix it up.

**Comment by jacobseiler** [comment]
@manodeep For the LHaloTree structure, should `FirstHaloInFOFgroup` ever be -1? I don't think it should be...

**Comment by jacobseiler** [comment]
This will actually have more severe consequences upstream. When I sort the forests, I sort on `forestID`, then `hostHaloID` and finally `Mass_200mean`.  Previously, this worked out nicely because all halos in the same FoF group (i.e., those with the same `hostHaloID`) would hence be sorted together.  Since they've been changed to `-1`, this messes the sorting up completely. 

One option would involve changing the values of `hostHaloID` to point to itself before we perform the sorting.

**Comment by manodeep** [comment]
(Did you just write and delete a comment?)

FirstHaloInFOFGroup can never be -1. Any halo (i.e., a FOF halo) can always point to itself. Unless, the semantics are now changed such that `FirstHalo` refers to `FirstSubhalo`, which is totally possible (fof halos without subhalos)

I am not sure what the intent was in the original tree files. Can you post a quick test that demonstrates that there are halos with `FirstHaloInFOFGroup==-1`?

**Comment by jacobseiler** [comment]
Yeah I pinged you asking if `FirstHaloINFOFgroup` could be `-1`.  Then I went and looked at your `LHaloTreeReader` code and saw you mentioned it there :P

```python
import h5py
import numpy as np

fname = "/fred/oz009/N1024/unifiedcatalogs/VELOCIraptor.tree.t4.unifiedhalotree.links.snap.hdf.data"
with h5py.File(fname, "r") as f:
    w = np.where(f["Snap_100"]["hostHaloID"][:] == -1)[0]
    print("There are {0} Halos with hostHaloID = -1 at Snapshot 100".format(len(w)))
    print("This is a fraction of {0:.3f}".format(len(w)/len(f["Snap_100"]["hostHaloID"][:])))
```

Output

```
There are 1437639 Halos with hostHaloID = -1 at Snapshot 100
This is a fraction of 0.896
```

**Comment by manodeep** [comment]
@jacobseiler Thanks!

@pelahi Is it possible for `FirstHaloInFOFgroup` to be `-1`? Will you please cross-check and confirm?

**Comment by pelahi** [comment]
@manodeep I don't know as my could does not produce this field. My guess is that if this field is initialized as -1, then if a FOF halo contains no substructure then it remains as -1. @jacobseiler what code produces this entry?

**Comment by jacobseiler** [comment]
@pelahi I believe @manodeep meant "Is is possible for `hostHaloID` to be `-1`?".

**Comment by manodeep** [comment]
@jacobseiler Now I see that you had tested for `hostHaloID`. That being `-1` is consistent with the LHaloTree notation. 

@pelahi Thanks!

**Comment by manodeep** [comment]
Sorry - `hostHaloID == -1`, is consistent with "Consistent Trees" convention and not LHaloTree convention. LHaloTree convention is `FirstHaloinFOFGroup == ArrayIndex` for denoting host halos. Thanks @jacobseiler for actually being awake...unlike me :D

**Comment by pelahi** [comment]
@manodeep hostHaloID == -1 simply indicates object is its own host halo. Instead of hostHaloID == ID I thought -1 would be better when it comes to compression.

**Comment by jacobseiler** [comment]
Ah ok, I'm following now.

It seems like the best fix for converting to LHaloTree format will be to first adjust `hostHaloID` to point to itself (for those objects who are their own hosts) before doing the sorting.

**Comment by jacobseiler** [comment]
Test returns 0 halos having `hostHaloID == -1` after this commit.

Leaving issue open until I include some Docs on the newly added function.

**Comment by jacobseiler** [comment]
Docs are now live.
